services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wargame
      POSTGRES_USER: wargame
      POSTGRES_PASSWORD: wargame
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "wargame"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wargame
      SPRING_DATASOURCE_USERNAME: wargame
      SPRING_DATASOURCE_PASSWORD: wargame

      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    
volumes:
  db-data:
